#' filename : qc-doublets-viability-by-cluster.r
#' Date : 2020-04-14
#' contributor : Yanshuo Chu

##libraries
suppressMessages({
    library(optparse)
    library(Seurat)
    library(ggplot2)
    library(ggpubr)
    library(rjson)
    library(rlist)
    library(tidyverse)
    library(facetscales)
})

option_list = list(
    make_option(c("-d", "--data"),
                type = "character",
                default = NULL,
                help = "rds file generated by load-cellranger.r",
                metavar = 'character'),
    make_option(c("-o",'--out'),
                type = 'character',
                default = 'doublets-viability-by-cluster-plot.pdf',
                help = 'output file name for the plot [default = %default]',
                metavar = 'character')
);

opt_parser = OptionParser(option_list = option_list);
opt = parse_args(opt_parser);

if(is.null(opt$data)) {
    print_help(opt_parser)
    stop("Input data must be provided", call. = F)
}


##load data
print('loading data')
seuratObj = readRDS(opt$data)

print('making plots')

gpdat = tidyr::gather(data.frame(rname = rownames(seuratObj@meta.data),
                                 seuratObj@meta.data),
                      key = type,
                      value = value, -rname, -seurat_clusters,
                      c('percent.mito', 'nFeature_RNA', 'nCount_RNA'))

temp.data <- filter(gpdat,type == c('percent.mito', 'nFeature_RNA', 'nCount_RNA'))
temp.data$seurat_clusters <- as.factor(temp.data$seurat_clusters)
temp.data$value <- as.numeric(temp.data$value)

plot.all = ggplot(data = temp.data, aes(x = seurat_clusters, y=value)) +
    geom_violin(aes(fill = seurat_clusters, color = seurat_clusters), width=1.3) +
    geom_boxplot(width=0.1, color = "white", alpha = 0.2, outlier.shape = NA) +
    xlab('seurat_clusters') + ylab('') +facet_grid(type ~ ., scales="free") +
    theme(axis.text.x = element_text(angle = 40,hjust = 1, vjust = 1),
          legend.position = 'none')

scales_y <- list(
    `percent.mito` = scale_y_continuous(limits = c(0, 0.15)),
    `nCount_RNA` = scale_y_continuous(limits = c(0, 5000), breaks = c(0, 200, 500, 1000, 3000, 5000)),
    `nFeature_RNA` = scale_y_continuous(limits = c(0, 2000), breaks = c(0, 200, 500, 1000, 2000))
)

plot.all.mini = ggplot(data = temp.data, aes(x = seurat_clusters, y=value)) +
    geom_violin(aes(fill = seurat_clusters, color = seurat_clusters), width=1.3) +
    geom_boxplot(width=0.1, color = "white", alpha = 0.2, outlier.shape = NA) +
    xlab('seurat_clusters') + ylab('') +facet_grid_sc(type ~ ., scales=list(y = scales_y)) +
    theme(axis.text.x = element_text(angle = 40,hjust = 1, vjust = 1),
          legend.position = 'none')

gpdat <-  as_tibble(data.frame(rname = rownames(seuratObj@meta.data), seuratObj@meta.data))
gpdat <- gpdat %>% group_by(seurat_clusters) %>% count()
gpdat$n <- as.factor(gpdat$n)

g <- ggplot(gpdat, aes(x=seurat_clusters, y=n, label=n, color=n))+
    geom_point() + geom_text(aes(color=factor(n)))

gp.list = list(plot.all, plot.all.mini, g)

ht <- 6
wh <- round(4/10 * length(unique(seuratObj@meta.data$seurat_clusters)))

if(ht < 3){ht = 3;}
if(wh < 5){wh = 5;}

do.call(ggarrange, c(gp.list, ncol = 1, nrow = 1)) -> combined.gp
pdf(opt$out,height = ht, width = wh)
print(combined.gp)
dev.off()

print('----end----')
